export const CREATE_GRADE = 'CREATE_GRADE';
export const GET_ALL_GRADES = 'GET_ALL_GRADES';
export const SELECT_GRADE = 'SELECT_GRADE';
export const SELECT_STUDENT = 'SELECT_STUDENT';
export const UPDATE_STUDENT_ROLL_NUMBER = 'UPDATE_STUDENT_ROLL_NUMBER';
